version: "2.4"
services:
  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    image: mysql:latest
    container_name: mysql
    env_file:
      - envs/mysql.env
    ports:
      - "5433:5433"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 10s
        retries: 10
  openskyetl:
    build:
      context: ./
      dockerfile: ./openskyetl/Dockerfile
    image: openskyetl:latest
    container_name: openskyetl
    env_file:
      - envs/python.env
    depends_on:
      mysql:
        condition: service_healthy
